### ISSUE TITLE
can't make pico work in a subfolder

### ISSUE THREAD

**Issue by the-drunk-coder** [picocms/Pico#193]
So, i installed pico in a subfolder (also, in my root folder, no difference), and when i call the folder like:

'www.mydomain.com/pico'

i always get a 404.

Calling 

'www.mydomain.com/pico/index'

works fine.

I've tried setting the base url in config.php, no success. Setting the DirectoryIndex in .htaccess either.

Any ideas ? In contrast to the related issues i read, subpages/folders work fine ...

**Comment by lf94** [comment]
Yes, I had the same issue. There were a couple of things that had to be corrected.

On debian sid:

1. Went into /etc/apache2.conf and added AllowOverride all to my /var/www/ folder.
2. a2enmod rewrite
3. service apache2 restart
4. Go to your Pico CMS installation. Make sure you have the .htaccess file! It is **NOT INCLUDED WITH THE .zip FILE**. If you don't have it, copy it from https://github.com/picocms/.
5. Now this is the step that really shot me in the foot. At this point you should be getting 403 errors. I did a chmod -R 777 to my folder, but you are better off handing your Pico CMS folders over to the apache user. Do chown -R www:www /your/pico/installation/folder.

I hope the maintainers post a guide for others, I spent 2 hours just scratching my head wondering why it wasn't working correctly. Never had this issue with Kirby CMS, another flat file based CMS.

**Comment by rafic20** [comment]
I'm stuck on this as well, getting 403 errors. I have `/pico` as a subfolder on my Apache webserver on DigitalOcean. 

I'm seeing that folders in some pages work, others  don't. See here: https://fuzzcrush.xyz/pico/

If you click "Sports" "Record Reviews", "Gigs" etc, those work fine. 

If you click "Blog", you'll get a blank screen (Firefox) or 404 message (mobile, Brave browser). Previously, I was seeing a 403 error, which could be fixed by using `/blog/index` as the URL instead of `/blog`

I have tried @lf94 's tips, but I'm confused as Pico was drag-and-drop simple before.
