### ISSUE TITLE
CommonMark

### ISSUE THREAD

**Issue by colinodell** [picocms/Pico#225]
Would there be any interest in switching to the [league/commonmark](https://github.com/thephpleague/commonmark) package for Markdown parsing?  It fully supports the [CommonMark standard](http://commonmark.org/).

**Comment by theshka** [comment]
Hi there, please have a look at these issues: #108, #168/#136

Since the markdown engine was recently switched from MarkdownExtra(0.8) to Parsedown-Extra(0.9), I don't think it's likely at this time. Also, as mentioned in #108, one downside of Pico is that it is not possible to replace the markdown parser, template engine or cache engine easily with a plugin.

**Comment by colinodell** [comment]
I couldn't help but notice [some recent issues with Parsedown](https://github.com/picocms/Pico/commit/8a44584291685e5e163765ed6578c184c991794e).  If you do end up reconsidering which Markdown parser you use, I'd be happy to answer any questions you have with CommonMark or assist with the implementation.  No pressure though - I completely understand that this project has its own set of goals and switch to CommonMark might not be one of them :)
