### ISSUE TITLE
First time clone and localhost Pico: Bunches of warnings

### ISSUE THREAD

**Issue by duongphuhiep** [picocms/Pico#248]
it is bad for first experience

( ! ) Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in D:\server\UwAmp\www\pico\Pico\lib\pico.php on line 189
Call Stack
#	Time	Memory	Function	Location
1	0.0000	139528	{main}( )	..\index.php:0
2	0.0020	267288	Pico->__construct( )	..\index.php:15
3	0.0030	284784	Pico->read_file_meta( )	..\pico.php:69
4	0.0030	285832	strtotime ( )	..\pico.php:189

**Comment by theshka** [comment]
Since PHP 5.1.0 (when the date/time functions were rewritten), every call to a date/time function will generate a E_NOTICE if the timezone isn't valid, and/or a E_WARNING message if using the system settings or the TZ environment variable.

You will need to setup your config.php file and uncomment the `date_default_timezone_set` line
