### ISSUE TITLE
Get Paragraphs with images inside

### ISSUE THREAD

**Issue by ungeruehrt** [picocms/Pico#266]
It seems like Pico is wrapping all images inside posts in paragraph tags. Is it possible to give these paragraphs a css class?

**Comment by theshka** [comment]
@ungeruehrt I believe it's Markdown that automatically wraps everything in the `<p>` tag, not Pico. 

Unfortunately, Markdown's image tag syntax does not support ids or classes. You could, however, use a regular HTML `<img>` tag in your `.md` and assign it a `class="foo"` then subsequently target it in CSS. 
```css
.foo {
     //your style
}
```

Otherwise, you would have to target all images within paragraphs using something like: 
 ```css
p > img {
      //your style 
}
```

**Comment by PhrozenByte** [comment]
The solution depends on what you're trying to do. If you just want to reference the image, wrap it into another element (selector is `.my-class img`):
```markdown
<span class="my-class">![Image of Octocat](https://assets-cdn.github.com/images/modules/logos_page/Octocat.png)</span>
```

Otherwise you can use a preceding reference element to really get the paragraph (selector is `.my-class + p`):
```markdown
<p class="my-class"></p>
![Image of Octocat](https://assets-cdn.github.com/images/modules/logos_page/Octocat.png)
```

**Comment by ungeruehrt** [comment]
Hi and thanks for your ideas.

Unfortunately the css solution doesn’t fit my needs because I definitely need to get the parent wrapping element. WordPress has a filter function for such cases – is there nothing close to that available with Pico?
