### ISSUE TITLE
Upgrading Pico 0.x to 1.0.0

### ISSUE THREAD

**Issue by smcdougall** [picocms/Pico#275]
(@PhrozenByte - `upgrade.md` mentions that users that have trouble upgrading should see a corresponding discussion here, which does not yet exist.  Made this issue to reserve the issue number, and I'll remove this comment later.)

Having trouble with your upgrade to 1.0.0?  If you've already checked out the [Documentation](http://picocms.org/docs.html) and could still use a hand, leave a comment below.  We'll check it out and see if we can't walk you through any difficulties.

Found a bug? Create a [new issue](https://github.com/picocms/Pico/issues/new) instead, so we can get to the bottom of it.

**Comment by PhrozenByte** [comment]
Hmm, what sentence do you mean exactly? The current content of the "What's new" section is meant to exist just temporarily and should be replaced completely. If someone experiences a problem while upgrading, he/she should refer to the ["Getting help" section](http://picocms.org/docs.html#getting-help), use GitHubs search engine and open a new Issue when necessary. Solving all problems in a single Issue (at worst multiple problems at the same time) makes things just more complicated, or what do you think?

**Comment by smcdougall** [comment]
At the [very end of the file](https://github.com/picocms/Pico/blob/gh-pages/upgrade.md) (in the commented section).  I'm trying to rework the whole document at the moment.  The discussion seemed like an okay idea.  Something to keep open for a little while during the transition.  A place for people to go "Help, I deleted my config accidentally and now my site won't load", or other issues that aren't tied to a bug.  I don't see it being busy enough to get *too* complicated, and wouldn't be any more difficult than a forum thread would anywhere else.

If you'd like though, I can rework it to reference the "Getting Help" section or just point to the Issues GitHub page.

**Comment by PhrozenByte** [comment]
Ah, I see. The problem is that a ordinary user usually doesn't know how to differ between "I have a question/a problem" and "This is a bug" - it's up to the developers to decide this. #272 is a good example for this :wink:

As long as everybody knows the difference it indeed makes things easier, but as soon as a user reports a bug in this Issue, we get into a hell of a mess. Using separate Issues also makes the whole process a little bit more structurized and makes linking to a specific problem and its solution easier.

Please always link to the "Getting Help" section, as this section describes how a user can help himself first before creating a new Issue.

**Comment by smcdougall** [comment]
Okay.  Sounds like a plan. :+1:
