### ISSUE TITLE
Plugin 0.x work on 1.x version?

### ISSUE THREAD

**Issue by edDimensi** [picocms/Pico#277]
Hi, I can hardly be called a developer, a maximum of html / css coder. In general, I do not know php. Not long ago I saw your cms and I liked its simplicity. But when you try to install the same pico_sitemap.php the latest version of pico cms, I did not receive sitemap.xml. Why? Because pico 1.x does not work with plugins 0.x? Sorry for my English, I use google translate
P.S.
And why is that links should look something like "http://mysite.com/?sup/index" I look like a "http://mysite.com/?sub%2Findex"

**Comment by PhrozenByte** [comment]
Pico 1.0 is backwards compatible to Pico 0.9 and 0.8, so old plugins should still be fully functional.

Pico 1.0 introduces a brand new routing system that is now compatible to any webserver. Even URL rewriting has become optional. Anyway, many old plugins (especially those which add new "pages" like `Pico_Sitemap`s `sitemap.xml`) don't know anything about this new routing system, so they still require you to enable URL rewriting.

Because you're asking about those "weird looking" URLs like `http://example.com/?sub/index`, I assume that you haven't enabled URL rewriting. Please make sure to also upgrade Picos `.htaccess` file and any other rewriting rules you configured in your webserver.

Please refer to the [upgrade tutorial](http://picocms.org/upgrade.html) on our website, Pico's [`.htaccess` file](https://github.com/picocms/Pico/blob/v1.0.0-beta.1/.htaccess#L7) and the [corresponding section in the docs](http://picocms.org/docs.html#url-rewriting).

**Comment by theshka** [comment]
Additionally, I also have a pull request on the Pico Sitemap plugin that is updated for the new version of Pico: https://github.com/DaveKin/Pico_Sitemap/pull/7

**Comment by edDimensi** [comment]
I turned on mod_rewrite in config.php and .htaccess file is put on your server. Now I have an old kind of links like "mysite.com/sub/page". I love it, thank you. But sitemap still does not work, it means that he simply does not support the 1.0 version and wait for a new version?
What about strange links "http://mysite.com/?sub%2Findex" why instead of "/" indicates to me "% 2F"?
I wrote the $ config ['rewrite_url'] = false; and used .htaccess you gave me and still links of this type mysite.com/?sub%2Fpage instead mysite.com/?sub/page. Why is / is replaced with% 2F? Thank you in advance

**Comment by PhrozenByte** [comment]
You must set `$config['rewrite_url'] = true;`in your `config/config.php` (as stated in the docs), not `false` (`false` = "don't rewrite URLs"). The `Pico_Sitemap` plugin works just fine with Pico 1.0 (even without @theshka updates), I tested it myself.

`%2F` is a side-effect of the routing method we use, it's a technical requirement, otherwise the URLs would be invalid. You wouldn't see this with enabled URL rewriting.

**Comment by edDimensi** [comment]
"You must set $config['rewrite_url'] = true;"  i do it. I have done so from the beginning, and I still do not what does not appear in the site root

**Comment by PhrozenByte** [comment]
We unfortunately can't help you when you don't give us some more information. As said previously, the plugin works just fine here.
1. What exact plugin are you using? Is it https://github.com/DaveKin/Pico_Sitemap?
2. What happens when you browse to `http://example.com/sitemap.xml` - a PHP error, a empty page, the `404.md` is shown?
3. Does `http://example.com/?sitemap.xml` work?
4. Can you still access your page contents?
5. Do internal links in your navigation look like `http://example.com/?sub/page` or `http://example.com/sub/page`?
6. When you browse to `http://example.com/sub/page`, does the desired page show up? If not, what shows up?
7. What PHP version are you using? Did you check the `error.log` of your webserver?

**Comment by edDimensi** [comment]
omg sorry, I thought I should have a file sitemap.xml, but it turns out it is available only at ...

**Comment by edDimensi** [comment]
Excuse me, but I really do not understand why I have everything right the first time is not going as it should. To test your pico cms I have used the services of service cloud9. After I installed the sitemap plugin to the virtual server, I will give this error "JsonWebTokenError: invalid signature". I tried to delete a file, but the error remained. I restarted the server, but the error remained. I ran the site through apache and php web server, but the error remained. It helps only the complete removal of the server. I tried to install the sitemap on your local server. And it worked without problems.

**Comment by PhrozenByte** [comment]
This isn't related to Pico, please refer to your webhoster (i.e. cloud9 customer service).

When browsing to the URL you provided, there's a fully functional Pico installation, including the `Pico_Sitemap` plugin. If you have any other problem or question, please don't hesitate to reopen this issue.
