### ISSUE TITLE
Release archive shouldn't include vendors directory

### ISSUE THREAD

**Issue by joshas** [picocms/Pico#289]
While it is still in beta, it is not major issue, but just wanted to point that out.

**Comment by theshka** [comment]
This is a had discussion, I'm afraid. Due to an outpouring of user feedback, we opt to include the `vendor` dir in release archives as to keep with Pico's "stupidly simple " mantra and provide "upload-and-go" functionality. We do however keep it out of the repo, and instruct developers to clone and run composer. Thanks for you feedback :)

**Comment by joshas** [comment]
Good idea, one step less for setup.
Just remove /vendor/twig/twig/.git/ directory in future releases, please.

**Comment by PhrozenByte** [comment]
Thanks @joshas for the hint about the `.git` dirs, reduces archive size from 8.41 MB to 339 KB  :flushed:

btw: The only difference between the release archives and Pico's source code actually is the additional `vendor` dir, so - as instructed in our `README.md`, the user docs and on the download page - you can safely download the source code and run `composer` yourself.
