### ISSUE TITLE
Having trouble running pico on Windows localhost

### ISSUE THREAD

**Issue by nem25** [picocms/Pico#322]
I'm running windows 10 and the latest pico version as of the date of this issue. I am using the built in web server of PHP version 5.6.17

I get the following error:

`Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in C:\Users\xyz\Development\pico-release-v1.0.0.tar\lib\Pico.php on line 501`

`Fatal error: Call to undefined function mb_convert_encoding() in C:\Users\xyz\Development\pico-release-v1.0.0.tar\vendor\erusev\parsedown-extra\ParsedownExtra.php on line 468`

**Comment by PhrozenByte** [comment]
Thank you for your bug report! This turns out to be a misconfiguration of your PHP installation. Please check your `php.ini` and set the [`date.timezone` option](https://secure.php.net/manual/en/datetime.configuration.php#ini.date.timezone) to a appropriate value. We'll suppress this warning in Pico 1.0.1. Additionally, Pico requires PHP's [`mbstring` extension](https://secure.php.net/manual/en/mbstring.installation.php) due to the use of [parsedown](https://github.com/erusev/parsedown), the Markdown parser Pico uses. Please make sure to use a PHP installation with `mbstring` enabled.

**Comment by nem25** [comment]
Great! That did it!
I also landed up using XAMPP which had everything set up properly.
Thanks!
