### ISSUE TITLE
Plugins not working

### ISSUE THREAD

**Issue by Senri88** [picocms/Pico#327]
I have a problem with plugins not working when i set content directory to "content" but when i use sample-content they work!

**Comment by PhrozenByte** [comment]
Do you really think we can help you with this kind of problem description? :wink: Please refer to [the Issues section of our `CONTRIBUTING.md`](https://github.com/picocms/Pico/blob/master/CONTRIBUTING.md#issues).

**Comment by Senri88** [comment]
Pico version 1.0.0, Plugins: pico_private, PicoEditor.
When i have installed the plugins nothing happens...

**Comment by PhrozenByte** [comment]
* What does "nothing" mean? Does the website show ...
  * a PHP error or exception? What does your webserver's `error.log` say?
  * a blank page? What does your webserver's `error.log` say?
  * Pico's example contents?
  * Pico's `404.md` ("Not Found")?
  * one of your webserver's error pages (403 Forbidden, 404 Not Found, 500 Internal Server Error)?
* What are the source/download URLs of the plugins you're using?
* What steps are necessary to reproduce the problem?
* What steps have you taken to solve the problem by yourself?

**Comment by Senri88** [comment]
The website displays normaly...
When i try to enter the editor i get 404
With the pico_private plugin im expecting to get a login prompt of some sort when i browse to the site but it just displays normaly...
pico_private: https://github.com/jbleuzen/Pico-Private
pico-editor:https://github.com/theshka/Pico-Editor-Plugin

**Comment by PhrozenByte** [comment]
As our `CONTRIBUTING.md` states:
> Concerning problems with plugins or themes, please refer to the website of the developer of this plugin or theme.

I'll try to help you anyway, but will tag this issue as `type: Invalid`.

The admin plugin seems to work with disabled URL rewriting only. So please try the following config in your `config/config.php`. Replace the `PicoEditor` `password` variable with the hash of your password (below is `foobar`), you can use [this website](http://crypo.bz.ms/secure-sha512-online) to generate it. You can then access the admin plugin from http://example.com/pico/?admin. Please make sure that your webserver has write access to your `content` directory, otherwise you can neither create nor edit any pages.
```php
$config['rewrite_url'] = false;
$config['PicoEditor'] = array(
    'enabled'   => true,
    'password'  => '0a50261ebd1a390fed2bf326f2673c145582a6342d523204973d0219337f81616a8069b012587cf5635f6925f1b56c360230c19b273500ee013e030601bf2425',
    'url'       => 'admin'
);
```

Please note that we'll release a official admin plugin with Pico 1.1, so please stay tuned.

Regarding the `pico_private` plugin: Works just fine for me. Please note that the plugin's default behavior is to protect only pages which set the meta variable `Private: true` (the `README.md` is a bit confusing about what's the default). Please read the plugin's `README.md` on how to configure this plugin!
