### ISSUE TITLE
Current URL

### ISSUE THREAD

**Issue by lostideaslab** [picocms/Pico#369]
Hi,
Thanks for very neat CMS.
I am developing a heavy website on Pico and I need to have access to the URI of the current page, I thought something like meta.id or page.id would work, but it looks like the page.id is only for pages ... any idea?

**Comment by PhrozenByte** [comment]
Hi and Welcome to Pico @lostideaslab!

I assume you're trying to use the current URL in a Twig template that isn't called through a page, but a plugin, correct?

At the moment we don't pass the request URL to Twig because this might create security issues (e.g. `{{ request_url|content }}` combined with a request like http://example.com/pico/../../../../etc/passwd and :boom:, we've a working exploit). Our problem here is that `Pico::$requestUrl` is intentionally just the raw string representing the request part of the URL the user requested. In contrast, `Pico::$requestFile` already references a (not necessarily existing) content file - and plugins may change this to something else, even to files outside the content dir. It might be a good idea to add something in-between to Pico 1.1... I'll think about that.

In the meantime you'll have to pass the URL on your own. What exactly are you trying to achieve?

**Comment by lostideaslab** [comment]
thanks for the explanations.
I'm migrating a website from WP to Pico and there are lots of nested directories.

Okay, I looked a bit around and I learned a little from the Breadcumbs plugin for Pico 0.x and here is a plugin I wrote that assigns two fictional parent and grandParent meta-s to current page:

```
<?php


class DParents extends AbstractPicoPlugin
{
	private $url = array();
    protected $enabled = true;
   
    public function onRequestUrl(&$url)
    {
        // your code
        $this->url = $url;
    }

    
    public function onMetaParsed(array &$meta)
    {
        // your code
        $parents = array();
        $parents = array_reverse(explode('/', $this->url));
        if (isset($parents[1])) {
	        $meta['parent'] = $parents[1];
        }
        if (isset($parents[2])) {
	        $meta['grandParent'] = $parents[2];
        }

    }

}
```

**Comment by PhrozenByte** [comment]
I'm still not sure what you're trying to achieve. How are you going to use the `parent` and `grandParent` keys?

**Comment by lostideaslab** [comment]
I use it to for navigation purposes, for example:

[here](http://lostideaslab.com/journal/6/brexit-scottish-love-letter ) is an article about "Brexit and Scotland" on the 6 issue of "The Lost Ideas Lab Journal": `lostideaslab/journal/6/brexit-scottish-love-letter.md`

Now on the top section of the page, you have this bar with the link "issue 6" so you can go back to the parent directory.

A future use from this key is going to be to display links to other articles from "issue 6" on the bottom of that article. If you don't know who is your parent, you don't know who are your siblings, but with this tiny piece of code **Pico** is much smarter. Now that article "brexit-scottish-love-letter.md" can call its siblings by name and they will be availabe for the user, if he or she want them too!

The main purpose of such this two keys are to be able to take advantage of opportunities that a flat file CMS provides in developing your theme.

**Comment by PhrozenByte** [comment]
Ah, I see, yeah, definitely makes sense. So it's about pages after all. You even don't need a plugin for that, you can achieve this with just Twig: :smiley:
```twig
{% set parents = current_page.id|split('/')|reverse %}
{% set parent = parents[1] %}
{% set grand_parent = parents[2] %}
```

Getting a page's siblings is easy, too:
```twig
{% set parent_path = current_page.id|split('/')|slice(0, -1)|join('/') ~ "/" %}
{% for sibling in pages if page.id starts with parent_path  %}
    {{ sibling.title }}
{% endfor %}
```

Using `page.id` is completely fine for that and doesn't expose you to the risk of security issues due to malicious request URLs :smiley:

**Comment by lostideaslab** [comment]
Exactly! Great!

I just thought current_page only works when you are listing pages ...

**Comment by PhrozenByte** [comment]
Pico actually doesn't differentiate between showing a single page and listing pages - Pico leaves this up to themes. If you have any other question, please don't hesitate to ask :smiley:
