### ISSUE TITLE
Pico doesn't work properly after installation

### ISSUE THREAD

**Issue by GabrieleZucca** [picocms/Pico#386]
Hi everybody, I've just downloaded Pico on my pc to give it a try.
When I try to access the main page with the browser (http://localhost/pico), I don't see the "expected" page, but the page you can see in the screenshot below.
I run Ubuntu 16.04, Apache 2.4.18 and PHP 7.0.18. I tried both pico 1.0.5 and 1.0.4.
![schermata del 2017-05-26 19-29-58](https://cloud.githubusercontent.com/assets/28986636/26505608/bb1e058e-4249-11e7-9064-cdcd6e47fb45.png)

**Comment by PhrozenByte** [comment]
Your webserver doesn't support PHP resp. PHP isn't enabled on your webserver. You'll need to enable PHP. If you e.g. want to use PHP with `mod_php`, install the `libapache2-mod-php` package. You can check your webserver configuration by creating a `info.php` in your httpdocs directory (e.g. `/var/www/html`) with the following contents. Open it in your browser, infos about PHP should show up. After you've installed/enabled PHP, Pico should work just fine.

```php
<?php
phpinfo();
```

**Comment by GabrieleZucca** [comment]
You were right, but even after installing both `libapache2-mod-php7` and `libapache2-mod-php` I keep getting the same result. PHP seems to be ok since the info.php page i created is working fine.

**Comment by PhrozenByte** [comment]
Try Ctrl + F5. Things like this can only happen when PHP isn't working at all, since your webserver is sending the raw contents of the `index.php`.

**Comment by GabrieleZucca** [comment]
[err.txt](https://github.com/picocms/Pico/files/1032646/err.txt)

**Comment by PhrozenByte** [comment]
Try installing the `php7.0-xml` package, not sure why this isn't installed by default on Ubuntu 16.04. You might have to restart Apache afterwards (`service apache2 restart`).

**Comment by GabrieleZucca** [comment]
Nothing to do, I keep getting the same result as before. This is the new errors:
[err.txt](https://github.com/picocms/Pico/files/1032781/err.txt)
I don't know if it can help, but I've also tried using Grav and it displays a page with the following error: 

> 'mbstring' extension is not loaded. This is required for Grav to run correctly

**Comment by PhrozenByte** [comment]
Heck, since when is Ubuntu's default LAMP installation *that* incomplete? 😒 All these packages are usually part of the default installation of a LAMP system (i.e. "recommended" in terms of `dpkg`/`apt`)... I've absolutely no idea why Ubuntu changed that 😕 

Anyway... Try installing the `php7.0-mbstring` package.

> I keep getting the same result as before

By "the same result" you don't mean that you get `run();` in your browser, but rather a completely white page, do you? Because the errors in the `error.log` and getting `run();` are mutually exclusive :smile: If not, try Ctrl + F5 (i.e. a force reload in your browser).

Nevertheless, we're getting closer... 😆 Maybe there are some more packages missing which should already be installed...

**Comment by GabrieleZucca** [comment]
It works! Thank you very much!

**Comment by PhrozenByte** [comment]
Great! 🎉 You're welcome!

If you have any other problem, please don't hesitate to create a new Issue, comment on this Issue or to join us on [#picocms at Freenode](https://webchat.freenode.net/?channels=%23picocms). Happy testing! :smiley:
