### ISSUE TITLE
Remove trailing slash for URL's in Pico

### ISSUE THREAD

**Issue by metzker** [picocms/Pico#399]
Hello!

I noticed that in Pico with default .htaccess settings 
/blog/article
and
/blog/article/

respond completely same page.
Since 2010 https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html
search engines recommend to set up 301 redirect to avoid duplicate content on a website.

So the problem is that I tried every single solution I found on the Web (10+ different ideas) I get perma-404 page from Pico or ERR_TOO_MANY_REDIRECTS from my browser.

Can you help me to set up my htaccess right way?
To clarify: 
I want all my pages like _/blog/article/_ to be 301-redirected to _/blog/article_ (get rid of trailing slash in the end).

My current .htaccess (default one)
`<IfModule mod_rewrite.c>
    RewriteEngine On

    # May be required to access sub directories
    #RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d

	RewriteRule ^(.*)$ index.php?$1 [L,QSA]
	RewriteRule ^(\.git|config|content|content-sample|lib|vendor)(/.*)?$ index.php?$0 [L,QSA]
    RewriteRule ^(CHANGELOG\.md|composer\.(json|lock)) index.php?404 [L]

    <IfModule mod_env.c>
        SetEnv PICO_URL_REWRITING 1
    </IfModule>
</IfModule>`

**Comment by PhrozenByte** [comment]
Pico always generates URLs without a trailing slash, so URLs with a trailing slash *should*n't exist. However, they definitely *do* exist sometimes. This mostly happens when humans manually edit URLs.

Search engines like Google can usually handle the duplicate content problem pretty well. However, personally I wouldn't rely on that either. You can (and should) add a `canonical` `link` Tag to your theme to help search engines like Google to understand your website's structure:

```twig
{% if current_page %}<link rel="canonical" href="{{ current_page.url }}" />{% endif %}
```

This solves the problem that search engines might see duplicate contents completely. If you additionally want to do a 301 redirect when encountering a URL *with* a trailing slash (the other way round isn't possible without extending the `Pico` PHP class, because Pico always *uses* URLs without a trailing slash), using `.htaccess` is the correct solution. Just to make this clear, you should add the `canonical` `link` Tag to your theme nevertheless you're using a 301 redirect or not 😉 

However, I wouldn't recommend using `mod_rewrite` in this particular case. `mod_rewrite` is about URL rewriting. It indeed also supports URL redirection, but is quite complex (especially when using multiple `RewriteCond` and `RewriteRule`) for this actually pretty simple task. So I rather recommend using `mod_alias`. Simply add the following to your `.htaccess`:

```apacheconf
RedirectMatch permanent ^/(.+?)/+$ /$1
```

dup of #391

**Comment by metzker** [comment]
Thanks.

I already use canonical to get rid of pagination problem (for pages like /page/2) in Pico pagination plugin.
Will it conflict with this one?

I tried to add RedirectMatch just as you said.
And i got
/blog/article is OK
/blog/article -> redirects to
`/blog/article?blog/article/`

What am I doing wrong?

**Comment by PhrozenByte** [comment]
Looks like URL rewriting isn't enabled. You have *added* the `RedirectMatch` to your `.htaccess` and left everything else unchanged, correct? Try adding `$config['rewrite_url'] = true;` to your `config/config.php` to force enabled URL rewriting.

> I already use canonical to get rid of pagination problem (for pages like /page/2) in Pico pagination plugin.
> Will it conflict with this one?

I guess not.

**Comment by metzker** [comment]
`$config['rewrite_url'] = true` already and URL rewriting is working i mean my URL are like
`site.com/blog/article` not like `site.com/?blog/article`
And if i delete `RewriteRule ^(.*)$ index.php?$1 [L,QSA]` it stops working and i get only site.com/?blog/article working

but after adding your proposed `RedirectMatch` i have this situation when trying to access trailing slash-ended urls.

I'm using shared hosting so i guess they can have some weird configs on their side... But what should i ask them to check?

**Comment by PhrozenByte** [comment]
Ah, indeed, I can now reproduce this issue. Pico 1.0's `RewriteRule` is interfering with `mod_alias` 😒 Since Pico 2.0 has a completely new routing system this won't be an issue with Pico 2.0. So, it seems like you must use `mod_rewrite` instead (sorry, my fault... 😞). Remove the `RedirectMatch` directive and add:

```apacheconf
RewriteRule ^(.+?)/+$ /path/to/pico/$1 [R=301,L,QSA]
```

I'll edit my answer above, so others aren't lead into the wrong direction.

**Comment by metzker** [comment]
I tried to add this Rule just before other rules and i got 404 on every page of the website.
So i added it after all RewriteRules.

And i still have problem that if i call trailing slash it redirects me to site.com/blog/article?blog/article

My .htaccess now

`<IfModule mod_rewrite.c>
    RewriteEngine On

    # May be required to access sub directories
    #RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d


	
	RewriteRule ^(.*)$ index.php?$1 [L,QSA]
	RewriteRule ^(\.git|config|content|content-sample|lib|vendor)(/.*)?$ index.php?$0 [L,QSA]
    RewriteRule ^(CHANGELOG\.md|composer\.(json|lock)) index.php?404 [L]
	RewriteRule ^(.+?)/+$ /home/chaguan/MYSITE.com/www/$1 [R=301,L,QSA]
	



    <IfModule mod_env.c>
        SetEnv PICO_URL_REWRITING 1
    </IfModule>
</IfModule>`

**Comment by PhrozenByte** [comment]
This is likely a caching issue of your browser (browsers cache 301 redirects, they are called "permanent" redirect for a reason 😄). Clear your browser's cache or try another browser/device.

> I tried to add this Rule just before other rules

You should add the rule to the top, right after the commented/unused `RewriteBase` directive. However, please note that both `RewriteCond` and the *first* following `RewriteRule` belong together, thus you mustn't add it between `RewriteCond` and `RewriteRule ^(.*)$ index.php?$1 [L,QSA]`, you should rather add it before `RewriteCond`.

btw, that's the reason why I suggested using `mod_alias` (what unfortunately isn't working so well together with Pico 1.0): `mod_rewrite` is sometimes a bit... hacky... and not intuitive at all...

**Comment by metzker** [comment]
it works! Thank you very much. Such a relief...

I think my problem was that I didn't know the rule:

> please note that both RewriteCond and the first following RewriteRule belong together

And that's why I tried 10+ different solutions and got zero result... 🤦
