### ISSUE TITLE
404 with empty first url parameter and rewrite_url

### ISSUE THREAD

**Issue by nliautaud** [picocms/Pico#447]
Hi,

It seems that Pico 2 with `rewrite_url` return a 404 when a page  is called with a first empty GET parameter.
```yml
/pico/page?foo # 404
/pico/page?foo=fine
```

Tested with a clean install, but not with different server configs.

Context : was testing the default `?output` of [Pico Output](https://github.com/nliautaud/pico-output). You can see the issue at http://pico.nliautaud.fr/PicoOutput

**Comment by PhrozenByte** [comment]
This is known and documented behavior. See http://picocms.org/phpDoc/v2.0.0/classes/Pico.html#method_evaluateRequestUrl

`QUERY_STRING` always takes precedence over `REQUEST_URI`, because we can't possibly be sure that `REQUEST_URI` actually works (if `REQUEST_URI` is `http://example.com/pico/`, is this due to not working URL rewriting, or because the user actually requested the index page?). There are some more reasons (like not making old URLs invalid when enabling URL rewriting, or for simple debugging reasons).

How about `?output=default`?

**Comment by nliautaud** [comment]
I see, thanks. Was using that as a shortcut feature, so that's not really important. Removed that.
