### ISSUE TITLE
Does not work in iPad

### ISSUE THREAD

**Issue by rollanders** [picocms/Pico#450]
I have Picocms installed on Nextcloud 13.4. I can only open part of first page in the default Wellcome manuscript,

**Comment by rollanders** [comment]
Do you mean that the default theme is compatible with Safari browser on iPad in other installations but not in the NC? That the issue is only related to the NC app?

**Comment by PhrozenByte** [comment]
Neither do I know whether the developers of the Nextcloud Pico CMS app made changes to the default theme or not, nor whether this is actually a problem with the theme or not - you provided *zero* information about what the problem is. I'm sorry, but I can't help you, because I simply don't know deeply enough what the Nextcloud app exactly does - I don't follow its development, it's a 3rd-party project.

Anyway, Nextcloud's Pico CMS app still uses Pico 1.0. We completely overhauled Pico's default theme with Pico 2.0 for a good reason, the old default theme was quite broken. No matter what: please refer to [`nextcloud/cms_pico`](https://github.com/nextcloud/cms_pico) for getting help. Either for making sure this problem isn't caused by the Nextcloud app, or for asking them to update the Nextcoud app to Pico 2.0.

**Comment by rollanders** [comment]
I reinstalled Pico CMS using these instructions https://www.c-rieger.de/nextcloud-meets-picocms/
Therafter I had no problems. It worked also in iPad. I guess the installation uses the latest version of Pico CMS, Thanks
