### ISSUE TITLE
Limited Levels of Concurrency in Lists

### ISSUE THREAD

**Issue by anasram** [picocms/Pico#462]
It seems like lists in markdown files doesn't accept more than 2 levels of concurrency. It should be unlimited or 6 at least.

e.g. The following list

```
* foo
 * foo
  * foo
   * foo
    * foo
```
will look like this:

* foo
  * foo
  * foo
  * foo
  * foo

**Comment by PhrozenByte** [comment]
Unfortunately I can't reproduce this. This Markdown

```md
* foo
  * foo
      * foo
        * foo
          * foo
```

results in

![bildschirmfoto von 2018-11-28 23-58-17](https://user-images.githubusercontent.com/920356/49188007-90210980-f369-11e8-9b6e-abf1a85a8b10.png)

The rather unexpected intendation of the 4th "foo" is likely due to the mixed whitespace intendation. This Markdown

```md
* foo
    * foo
        * foo
            * foo
                * foo
```

reslults in

![bildschirmfoto von 2018-11-29 00-01-40](https://user-images.githubusercontent.com/920356/49188142-f7d75480-f369-11e8-8798-ee56caaf9f8e.png)
