### ISSUE TITLE
Converting quotation marks to a <q> element

### ISSUE THREAD

**Issue by anasram** [picocms/Pico#463]
Just like when markdown language converts &#96;foo&#96; to `<code>foo</code>`, I propose to convert `"foo"` to `<q>foo</q>`.

**Comment by PhrozenByte** [comment]
Pico uses [Parsedown](http://parsedown.org/) as Markdown parser, so to put a long story short: Regarding Markdown, Pico does, what Parsedown does. Due to very limited time, we don't plan to create our own Markdown parser.

Anyway, customization is one of Pico's main advantages. You can use Pico's `onParsedownRegistered` event to hook into Parsedown's processing. See [Parsedown's wiki](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions) for more info about how to create a Parsedown extension and how to add your own syntax rules to Parsedown.

**Comment by anasram** [comment]
I just submitted it here:
https://github.com/erusev/parsedown/issues/684
