### ISSUE TITLE
Pico cms facebook group

### ISSUE THREAD

**Issue by ctuxboy** [picocms/Pico#466]
Hello guys,

(I don't know if it the right place here for sharing this)

I'm a new Pico-user, but couldn't find a forum for some helping hand.
Okay, it is 'stupidly simple' but sometimes it is handy asking or helping others.
I hope that this facebook group can help others for building websites, themes, plugins,...
If it can sharing the link below:

[PicoCMS group](https://www.facebook.com/picocms )

Thanks a lot!

Regards,
Christophe

**Comment by PhrozenByte** [comment]
Since we couldn't (and don't really wanted to) prevent users from using GitHub as some sort of support forum, we simply made the decision to officially use GitHub for any kind of support request, not just for bug reports and feature requests. So, please don't hesitate to open a new Issue on GitHub if you have any question about Pico, including support requests.

Naturally this is no final decision - we all hope that Pico's community grows, so there might be the point when we really need a forum, mailing list or something like that, but we're not at this point yet.  The only other official support channel besides GitHub is [#picocms on Freenode IRC](https://webchat.freenode.net/?channels=%23picocms) (although the channel is often idle). Also see http://picocms.org/docs/#getting-help

Thank you for creating the Facebook group! Help is always appreciated and I'd love to see when you help others to use Pico :heart:

**Comment by ctuxboy** [comment]
Hello @PhrozenByte ,
Thanks that you appreciate this.
I love this awesome cms, really good work.
It is really 'stupidly simple' cms but sometimes a helping hand is very handy.
Thanks for the tip about adding issues on Github :)
I'm not a pro developer, but i can helping myself with simple code (HTML, CSS, PHP, a little knowlegde of twig,...) so this cms is really nice!!!
