### ISSUE TITLE
Update PicoCMS

### ISSUE THREAD

**Issue by ctuxboy** [picocms/Pico#468]
Okay,
Next step!

I have SSH access to my hosting.

Follow the steps installing Picocms with composer.

Now i have access to PicoCMS with this url:
`https://my_domain.be/pico-composer/ `

1. How can i set Picocms in the root folder? Just copy the files in the webroot?
2. What is the reason accessing pico in a subdir **/pic-composer/**?

**Comment by PhrozenByte** [comment]
1. Yes, you can safely move/copy all of Pico's file to a different directory (including webroot of course)

2. This is due to how `composer create-project picocms/pico-composer` works. Unfortunately we can't really change that. However, I guess the install instructions can be made more precise here. I'll update them accordingly, thank you for your feedback! :+1:

**Comment by Lomanic** [comment]
I did not test it but `composer create-project picocms/pico-composer .`  should create the files in the current directory instead of `./pico-composer`.

**Comment by PhrozenByte** [comment]
That's correct @Lomanic. However, since we unfortunately can't assume that Composer is installed globally, we recommend users to download `composer.phar` first. Unfortunately the guys from Composer didn't decide to treat a directory with just the `composer.phar` in it as not "empty enough" and let Composer bail out...

@ctuxboy isn't the first user stumbling over this, thus I think it's better to update the docs accordingly. On occasion I also updated the install instructions for developers :smile:  See 8826bf4bfed59cffac5a5f53fdc3f38db668e815 resp. https://github.com/picocms/picocms.github.io/commit/39bb74290b2aa0c07baaedbe55c418654031c6ee

**Comment by ctuxboy** [comment]
UPDATE:
I read the changes in the [Readme.md](https://github.com/picocms/Pico/commit/8826bf4bfed59cffac5a5f53fdc3f38db668e815) now it's clearify.

Installed PicoCMS directly in the webroot using composer with success!!!!
