### ISSUE TITLE
How to make img relative path work?

### ISSUE THREAD

**Issue by greencopper** [picocms/Pico#493]
Hi,

We're using picocms at our office on our intranet. People are using editors such as Retext to write the Markdown and we really need to enable relative paths so that Retext and other editors displays images correctly. We cannot use absolute paths.

I am considering hacking picocms, but since I can see this feature has been requested several times, I think it's much better to enable this using a setting in the configuration.

Before traversing the entire codebase in order to locate the relevant code I want to ask where the code dealing with paths resides and if there is an easy "hack" to make relative paths work when needed?

Kind regards.

**Comment by PhrozenByte** [comment]
Actually there's no code dealing with paths in Markdown files in Pico, all paths (including relative paths) are taken as-is (even `%base_url%` is just a placeholder that is replaced by Pico's base URL before parsing Markdown). So, if you use a link like `![Cats](assets/cats.jpg)`, Pico will parse this to `<img src="assets/cats.jpg" alt="Cats" />`. After adding a appropriate `base` HTML attribute (e.g. `<base href="{{ base_url }}" />`) to the `<head>` of your Twig templates (e.g. `themes/my_theme/index.twig`), relative paths like the one shown above work just fine.

The problem is that ReText doesn't know anything about this and interprets paths relative to the current file. So, for example, if there's a `![Cats](assets/cats.jpg)` in `content/sub/page.md`, what file is supposed to be included? It should be `assets/cats.jpg`, however, since ReText treats all paths relative to the current file, it thinks the path is `content/sub/assets/cats.jpg`. This won't work for obvious reasons, in ReText you'd need a path like `../../assets/cats.jpg`, resulting in `content/sub/../../assets/cats.jpg` (equals `assets/cats.jpg`).

You could write a simple Parsedown extension (hook into `Parsedown::inlineLink()`) to change relative URLs like `../../assets/cats.jpg` to `%base_url%/assets/cats.jpg`.

Try something like the following (untested code):

```php
class ParsedownRelativePicoPlugin extends AbstractPicoPlugin
{
    public function onParsedownRegistered(Parsedown &$parsedown)
    {
        $config = $this->getPico()->getConfig();

        $parsedown = new ParsedownRelative();
        $parsedown->setPico($this->getPico());
        $parsedown->setBreaksEnabled((bool) $config['content_config']['breaks']);
        $parsedown->setMarkupEscaped((bool) $config['content_config']['escape']);
        $parsedown->setUrlsLinked((bool) $config['content_config']['auto_urls']);
    }
}

class ParsedownRelative extends ParsedownExtra
{
    protected $pico;

    public function setPico(Pico $pico)
    {
        $this->pico = $pico;
    }

    public function getPico()
    {
        return $this->pico;
    }

    protected function inlineLink($excerpt)
    {
        $link = parent::inlineLink($excerpt);
        if ($link === null) {
            return;
        }

        $href = $link['element']['attributes']['href'];
        if (($href[0] !== '/') && !preg_match('#^[A-Za-z][A-Za-z0-9+\-.]*://#', $href)) {
            $basePath = $this->getPico()->getRequestFile();
            $targetPath = $this->normalizePath(dirname($basePath) . '/' . $href);

            $rootDir = $this->getPico()->getRootDir();
            $rootDirLength = strlen($rootDir);
            if (substr($targetPath, 0, $rootDirLength) === $rootDir) {
                $baseUrl = $this->getPico()->getBaseUrl();
                $link['element']['attributes']['href'] = $baseUrl . substr($targetPath, $rootDirLength);
            }
        }

        return $link;
    }

    protected function normalizePath($path)
    {
        $path = str_replace('\\', '/', $path);
        $pathParts = explode('/', $path);

        $result = array();
        foreach ($pathParts as $pathPart) {
            if (($pathPart === '') || ($pathPart === '.')) {
                continue;
            } elseif ($pathPart === '..') {
                array_pop($result);
                continue;
            }
            $result[] = $pathPart;
        }

        return implode('/', $result);
    }
}
```

**Comment by LetOpDrempels** [comment]
Hello PhrozenByte, i am trying to understand what you wrote there. Basically what you described is exactly what i am looking to do, replace `../../assets/cats.jpg` with either `%assets_url%/cats.jpg` or `%base_url%/assets/cats.jpg` if that'd make more sense. Unluckily your description of a solution is very unclear to me, as to where and how i would have to play with the piece of code you wrote there.

What i did was "create" a plugin called ParsedownRelativePicoPlugin with the code you wrote. The image URLs in the html still look like `../../assets/cats.jpg`. Now i am not sure if it's something to do with the code (i can't really understand it), or if i wasn't meant to make a plugin out of that code but something else. Could you please elaborate a bit more on what i may be doing wrong?
