### ISSUE TITLE
Deploying to Azure Linux Web App Error 500

### ISSUE THREAD

**Issue by kamsalisbury** [picocms/Pico#520]
The current pre-bundled release pico-release-v2.1.0.zip does not currently produce a ready to run installation.

Deploying the pre-bundled release pico-release-v2.1.0.zip to Azure Web App (Linux) via private git repository produces an error 500.
`PHP Warning:  require_once(/home/site/wwwrootvendor/autoload.php): failed to open stream: No such file or directory in /home/site/wwwroot/index.php on line 25`

This is because .gitignore says to ignore /vendor.

After editing .gitignore, pushing to repo, error 500 continues.
```
PHP Warning:  include(/home/site/wwwroot/vendor/composer/../../plugins/PicoDeprecated/PicoDeprecated.php): failed to open stream: No such file or directory in /home/site/wwwroot/vendor/composer/ClassLoader.php on line 444
[php7:warn] [pid 40] [client 172.16.xxx.xxx:28367] PHP Warning:  include(): Failed opening '/home/site/wwwroot/vendor/composer/../../plugins/PicoDeprecated/PicoDeprecated.php' for inclusion (include_path='.:/usr/local/lib/php') in /home/site/wwwroot/vendor/composer/ClassLoader.php on line 444
[php7:error] [pid 40] [client 172.16.xxx.xxx:28367] PHP Fatal error:  Uncaught Error: Class 'PicoDeprecated' not found in /home/site/wwwroot/vendor/picocms/pico/lib/Pico.php:596\nStack trace:\n#0 /home/site/wwwroot/vendor/picocms/pico/lib/Pico.php(548): Pico->loadComposerPlugins()\n#1 /home/site/wwwroot/vendor/picocms/pico/lib/Pico.php(424): Pico->loadPlugins()\n#2 /home/site/wwwroot/index.php(39): Pico->run()\n#3 {main}\n  thrown in /home/site/wwwroot/vendor/picocms/pico/lib/Pico.php on line 596
```
A quick visual check shows many sub-folders missing from /vendor/composer.

**Comment by PhrozenByte** [comment]
I guess a few things got mixed up here.

If you want to use Pico's pre-bundled releases, you don't use Git. You just upload the files to your webserver (Azure in this case) and you're ready to go. Just refer to the ["I want to use a pre-bundled release" section of Pico's `README.md`](https://github.com/picocms/Pico#i-want-to-use-a-pre-bundled-release).

If you rather want to manage your website in a Git repo, you use [Pico's Composer starter project](https://github.com/picocms/pico-composer) as a basis. Simply fork the repo. It's fully intentional that Composer's `vendor` dir is in Pico's `.gitignore`, the `vendor` dir isn't supposed to be commited. If you want to fix the versions of your dependencies, you can commit Composer's `composer.lock` instead, but keep in mind to update your `composer.lock` from time to time. Then you can clone your fork on your webserver (i.e. Azure). However, this still won't give you a working Pico installation. You still have to run `composer install` to download and install Pico's dependencies (it basically creates the `vendor` dir and `composer.lock`). Just refer to the ["I want to use Composer" section of Pico's `README.md`](https://github.com/picocms/Pico#i-want-to-use-composer).

But I guess there should be separate instructions on how to manage a Pico website in a Git repo, too many people are still forking `picocms/Pico`, even though they should rather fork `picocms/pico-composer`. I'll update Pico's `README.md` and website accordingly.

**Comment by kamsalisbury** [comment]
Found the issue on my end.
The pre-bundled release has composer.json and composer.lock files, which Azure DevOPS "sees" in the build pipeline and then automatically processes them. And fails. I guess, the build pipeline is trying to help but I never said to process those files! Because the build failed, it never updates the website with each git push.
Removing composer.json and composer.lock allows the CI/CD pipeline to update the website with each push as expected.
Azure DevOPS is really new to me. Thanks for replying because it led me to understand their build pipeline processes better.
