### ISSUE TITLE
Nextcloud & Pico = Erreur interne du serveur

### ISSUE THREAD

**Issue by cr9christi9n** [picocms/Pico#540]
Hi there,
I installed Pico on Nextcloud 18.0.3 and as soon as I try to modify index.md (with sample_pico templates) I get the folowing error in web page

> Erreur interne du serveur
La page demandée du site Web n'a pas été créée, le serveur n'a pas pu traiter votre demande.

wich is an error from the server.
So impossible to access web pages index.md.

**Comment by PhrozenByte** [comment]
Please refer to https://help.nextcloud.com/c/apps/cms-pico/128 for getting help about Pico CMS for Nextcloud. This is the repository of Pico. You can find the app's repository here: https://github.com/nextcloud/cms_pico. Since I can't transfer issues from this repo to the `cms_pico` repo, please open a new issue there. When doing so please also attach your Nextcloud log.

**Comment by cr9christi9n** [comment]
Hi,
OK, thanks
