### ISSUE TITLE
php 8 and pico not good

### ISSUE THREAD

**Issue by tuckson** [picocms/Pico#584]
When running a default install of pice on xampp with php 8 I get this error:
Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\portable\XAMPP\xampp\htdocs\pico\vendor\twig\twig\lib\Twig\Node.php on line 42

Now in version 7 this Unparenthesized  stuff was named 'depreceated' already, so  the current pico will not run on php 8. I suppose

**Comment by PhrozenByte** [comment]
Please try [Pico v3.0.0-alpha.2](https://github.com/picocms/Pico/releases/tag/v3.0.0-alpha.2). There are no functional changes in comparison to stable v2.1.4 besides updated dependencies (which come with some, but rather small functional changes). This version is safe to use in production due to the very limited changeset, specifically aiming for Pico to support PHP 8.0+.
