### ISSUE TITLE
theme_url - where I can find details how its obtained?

### ISSUE THREAD

**Issue by dawidmachon** [picocms/Pico#609]
Hi, I am starting using Pico, but have problem with css files and links - they have port on the end. Example:
`https://mydomain.com:80/themes/default/css/style.css`

As i found links for these styles in default theme are created by variable _theme_url_.
`{{ theme_url }} - The URL to the currently active theme`

Could you guide me where to looking for issue? It's a fault of reverse proxy, because these variable is taken from headers or something different?

**Comment by mayamcdougall** [comment]
@dawidmachon Did you ever get a chance to try this?  Pretty sure the `http://` was all you needed.

Since you've also got #610 open for general help, we can close this Issue if you're done with it.

If I don't hear back from you, I'm just gonna let the `github-actions` bot close this Issue next time it tries.

We can keep chatting over on #610 if you need any more help though. 😁

**Comment by dawidmachon** [comment]
Of course! Closed. I am still investigating this stuff, but your solution solving it for sure!

**Comment by PhrozenByte** [comment]
> If you set `base_url: mydomain.com` in your `config.yml`, it should fix the issue for you.
> 
> It's not the _best_ solution, since all you're doing is hardcoding the url, but it should get rid of the port number for you.
> 
> (@PhrozenByte, whenever you get back, I'd love to know if you have a better solution for this or if you'd consider my workaround the "proper" fix.)

Sorry for the late response. That's due to a discrepancy regarding the use of HTTPS: The webserver / PHP tells Pico that HTTPS is enabled, but communication goes through port 80 (i.e. the HTTP port). Since port 80 is a non-default port for HTTPS it is appended to the guessed base URL. The correct solution is indeed to configure `base_url` manually.

**Comment by mayamcdougall** [comment]
> That's due to a discrepancy regarding the use of HTTPS

Ah, yeah, that makes since in a reverse proxy setting then. 👍🏻

I'll make a note of that in the Docs rewrite. 😉

I didn't have `config.yml` broken out into explanation, since it's documented well inline.  Maybe there's room for a section on it though.  Just for quirks like this. 🤔

(The *use case* being the quirk I mean, not Pico's behavior. 😉)
