### ISSUE TITLE
Admin Panel stopped working

### ISSUE THREAD

**Issue by tim128er** [picocms/Pico#636]
Hello,

I took over the website of a friend, who is a restaurant owner. Even though I know some programming languages, I encountered a problem I cant fix. 

When I open the admin panel of the website (https://lagallerie-mainz.de/admin) I am no longer able to edit the content. I still see every text I was able to edit, but the HTML editor doesnt load up anymore. If I edit the .md files manually over my FTP connection, I am still able to change the content. The problem is, that my friend has no programming skills and needs that graphical UI and HTML editor.

If someone has an idea, why the admin panel stopped working, I (and my friend, the owner) would be very happy!

Sincerely
tim128er

**Comment by tim128er** [comment]
Seems like this plugin is installed for the admin panel. The pico version is 1.0.6

![image](https://user-images.githubusercontent.com/37018916/167956248-f8b2df84-2331-4503-8056-00451954eacb.png)

**Comment by PhrozenByte** [comment]
Unfortunately we can't provide support for 3rd party plugins, please refer to the respective plugin developer to get help.

**Comment by ctuxboy** [comment]
@tim128er i try also this editor-plugin, but it has some issues, i can create an md-file (subpage) in the editor, but the md-file saved to websites root, i don't know why, but on this way it is not useful :disappointed:
Looking if i can add an issue by the developer, but can't find a way do that on [plugin's github-page](https://github.com/astappiev/pico-editor)

**Comment by mayamcdougall** [comment]
There are **so many** forks of that plugin too.  Unfortunately, none of them seem to be maintained at the moment.

@ctuxboy, The one you linked specifically has "Issues" turned off for the repo, but I'm not even sure if this was intentional, or carried over from the *previous* repo that they forked.

Generally, every time someone new comes along, they fork it, update it for their own usage... and subsequently abandon it shortly after. 😔

It would be really nice if there was a currently maintained version of this we could point to, as having an admin interface with Pico would make it much more accessible (it's just not something we can *officially* support at the moment).

---

@tim128er Maybe adopting a different workflow could help with this?  Although it's a heavier (and indeed, overkill) solution, Pico for Nextcloud can be set up as a more user-friendly alternative.  I'm not fluent in the details there, as I'm pretty sure there's also only *certain* Markdown editors for Nextcloud that play nice with Pico.  Still, it's an option.

Another idea could be replacing FTP in this setup with a syncing solution (eg, a lighter one than Nextcloud).  I've had good luck in the past with syncing Pico's `content` and `assets` folder to my local machine and just using a text editor to manage my Pico sites instead.

I actually used Nextcloud at the time (which was before Pico for Nextcloud existed), but you could probably set something up easily with Syncthing depending on your hosting situation.

Just some food for thought.  Ik it's not the answer you're looking for. 😅
