### ISSUE TITLE
Show total pages from a specific template

### ISSUE THREAD

**Issue by ctuxboy** [picocms/Pico#638]
In [twig](https://twig.symfony.com/doc/2.x/filters/length.html) there is a filter for showing the number of pages:

`{{ pages|length }}`

Shows the total for **ALL** the pages.

Is it also possible in Pico count the pages with a specific template?
Try this, but doesn't work:

`{{ pages("TEMPLATE")|length }}`

I think it is possible with a for loop, but is not very efficient, i mean not good for performance.

**Comment by vodkafilm** [comment]
> The length filter returns the number of items of a sequence or mapping, or the length of a string.

So `{{ "number"|length }}` return 5 and `{{ pages("yoursubdir")|length }}` return the number of pages in your subdir.

**Comment by ctuxboy** [comment]
> > The length filter returns the number of items of a sequence or mapping, or the length of a string.
> 
> So `{{ "number"|length }}` return 6 and `{{ pages("yoursubdir")|length }}` return the number of pages in your subdir.

I read thé docs about thé pages()~function. The problem is that i have pages with the specific templates exist in different dirs, so it not only in one dir. 

/province-1/city-1/**location-1.md**
/province-1/city-1/**location-2.md**
...
/province-1/city-2/**location-1.md**
...
/province-2/city-1/**location-1.md**
...
/province-x/city-x/**location-x.md**

I want thé total numbers of pages with template:'*location*'

**Comment by ctuxboy** [comment]
Now i do it this way:

```
{% set count = 0 %}
{% for page in pages %}
  {%- if page.meta["template"] == 'location' %}
    {% set count = count +1 %}
  {% endif -%}
{% endfor %}
**Total locations:**  {{ count }}
```

This works perfect! Next step is adding this in a macro for reuse for showing total **cities** :smiley:

I'm afraid, the only issue is the performace, i have several for-loops on some pages, with 500+ pages i'm affraid, maybe it speeds down the website. Someone knows if it's possible caching variables in Twig?

**Comment by vodkafilm** [comment]
`page in pages` is not recommended for sites with many pages, `page in pages()` is faster

```
{% set loc = '' %}
{% for page in pages("",offset=3) %}
    {% set this = page.id|split("/")|slice(1, 1)|join %}
    {% if this starts with 'location' %} {% set loc = loc + 1 %}{% endif %}
{% endfor %}
{{ loc }}
```
_Change the offset for the right content._

But why not a meta tag `location`?

in your .md add:
```
---
location: true
---
```
and in twig:
```
{% set loc = '' %}
{% for page in pages("",offset=3) %}
    {% if page.meta.location %} {% set loc = loc + 1 %}{% endif %}
{% endfor %}
{{ loc }}
```

**Comment by ctuxboy** [comment]
@vodkafilm thanks for the 'golden' tip :smiley:
Fast reply...
Okay i try this this evening ir tomorrow.
I use this metadata in the md-files for the location _(in my project is the template-name 'dogzone' instead of 'location', but using 'location' looks more default, and maybe better if it can help others)_:

```
---
template: location
---
```

Is your solution **location: true** a better solution or it doesn't matter?

Anyway i try using your suggestion with the pages()-function if it gives better performance :+1:

Here you can see what i try to build...
![Screenshot 2022-05-14 11 50 19](https://user-images.githubusercontent.com/10013632/168420704-dbb7de45-6d67-4099-8004-9e99503a3590.png)

And that's the original website: [dogvalley.be](https://dogvalley.be/)

**Comment by vodkafilm** [comment]
It all depends on the type of information you want to process. If you need to know only if the .md file is dedicated to a location the logic is true / false.

`location: true`
`{% if page.meta.location %}this is a location{% endif %}`
_this is a location_

 If you also need to know what kind of location then you can add more info like:

`location: city`
`{% if page.meta.location %}this is a {{location}} location{% endif %}`
_this is a city location_

**Comment by ctuxboy** [comment]
Ah okay,
Thanks for the info.
I using three templates **province.twig**, **city.twig** and **location.twig**
So that was the reason i using template: **province**/**city** or **location** :smiley:

**Comment by vodkafilm** [comment]
Your code is right, but the `if` is more _future-proof_ because if you add some others type of .md file you are sure to count only the pages with the right meta tag.

**Comment by mayamcdougall** [comment]
Sorry, been away for a couple days, so I didn't get a chance to comment here before.

Unfortunately, as far as I know, you've indeed run into a limitation of Twig.  Sometimes there's just no way to get the data you want without iterating.  And with a large number of pages too, this ends up being a worst case scenario. 😔

`pages()` is indeed faster than `pages`... but that's because it allows you to limit the scope of what you're looking through.  If you're still iterating over a large number of pages, it might not be much faster.

The only really *quick* way to do this counting would probably be to write a plugin for it (I can't really help with that though, sorry. 😅).

But ultimately, you'll have to just try it and *see* what the performance is like.  "Slow" is always a relative thing too... as we're usually still talking about a couple MS of delay.  In the end, the small performance impact might not *actually* matter.

**Comment by ctuxboy** [comment]
> Your code is right, but the `if` is more _future-proof_ because if you add some others type of .md file you are sure to count only the pages with the right meta tag.

Ah okay, a 'double check'. Good tip!

**Comment by ctuxboy** [comment]
@mayamcdougall ,
Hmmm develop a plugin? It's tot difficult at this (beginning) stage for myself :wink:
I will test it with a lot of pages, and indeed the speed is 'relative', if it slow down the website <= 1sec, this is not a 'worst case', there are a lot of websites loads in more than 5sec :smile:

**Comment by PhrozenByte** [comment]
I don't really have to add much to the discussion here, just to clear this up: A plugin won't be any faster. Plugins aren't any faster unless they actually do something else to accomplish the same. Unless you choose to change your directory structure this is indeed the best solution possible.

**Comment by mayamcdougall** [comment]
@PhrozenByte Interesting. Good to know. 🤔

You're always quick to suggest running complex operations in a plugin rather than Twig, so I guess I just *assumed* something could be done a little quicker (or smarter) using PHP directly (eg, even if you're still stuck iterating over everything, at least you're doing it directly in PHP, not through the extra layer of Twig code being converted to PHP operations).

My bad. Shouldn't have assumed. 😅

**Comment by vodkafilm** [comment]
@mayamcdougall I think a plugin should be a solution for common task, meanwhile a twig code should be specific for the theme template

**Comment by PhrozenByte** [comment]
Since Twig still is pretty limited on what you can do with it, you can often implement things differently with PHP - things get faster not because it's written in PHP, but due to other - faster - algorithms. If you end up doing exactly the same (iterating all pages to count pages matching some criteria) it won't really be any faster.

**Comment by mayamcdougall** [comment]
> I think a plugin should be a solution for common task, meanwhile a twig code should be specific for the theme template

Agreed. But if there were a way it could help, it could have been worth doing.

> things get faster not because it's written in PHP, but due to other - faster - algorithms.

Yeah, that makes sense.  I wasn't *actually* thinking it through when I suggested it. 🤷🏻‍♀️ 😅

**Comment by ctuxboy** [comment]
Thanks for all the explanation.
I try it soon build this option with php.
