### ISSUE TITLE
Google doesn't find my website 

### ISSUE THREAD

**Issue by promexio** [picocms/Pico#649]
Hi, 
I have released a small Website. 
After having removed the tags noindex, nofollow and added my page to the google search index, 
the website doesn't appears, even when I search directly on google by site:""  

Have you any idea how to solve that? 
Another wordpress site on the same server works fine. 

Cheers

**Comment by PhrozenByte** [comment]
Unfortunately we can't really help you with your SEO, simply because Pico can't really do anything about it. It's all up to you, your theme and your contents.

However, here are a few quick tips: Google doesn't necessarily pick up new websites immediately. You might want to improve your chances by hinting Google about your website using Google's Search Console. Furthermore you might wanna add a sitemap, see e.g. [`phrozenbyte/pico-robots`](https://github.com/PhrozenByte/pico-robots).

**Comment by promexio** [comment]
Ah. Thx. I thought there might be any other setting I haven't found yet. 
But if the noindex,nofollow tag in the header section is the only way to exclude PICO Webpages to be found, it should really be sth related to my content.
