### ISSUE TITLE
pico in IPFS?

### ISSUE THREAD

**Issue by codehangen** [picocms/Pico#654]
Hi all.

I would like to know if it would be possible to host picocms in ipfs.

**Comment by mayamcdougall** [comment]
Sorry that this sat for so long without being answered.  It's kind of an out-of-scope question for Pico, since it's really about web server setup and not Pico itself.

I've never done anything with IPFS, but some quick googling suggests that no, IPFS server software does not tend to utilize PHP in any way.  IPFS is just a protocol though, so theoretically if you had a web server software that *did* serve PHP over an IPFS connection, Pico would probably work.  There seems like there might also be some more "hacky" ways to script your IPFS software to pre-process and render your PHP files before sending the rendered output, but that's probably not the safest or most feasible solution.
