### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by gitgit2019** [picocms/Pico#677]
I see the official files last edited years ago. I need a very simple CMS but I'm not sure if this is dead project I should use for my project?

**Comment by Croydon** [comment]
This branch: https://github.com/picocms/Pico/tree/pico-3.0 is a bit more active, but it seems like there is an artificial blockage to finally make a new release, which would be long overdue.

**Comment by PhrozenByte** [comment]
As @Croydon explained there's a Pico 3.0 release dangling for quite a while now, but it's currently blocked due to stuff not really related to Pico's core (like broken CI, untested backwards-compatibility, missing docs, incomplete upgrade instructions, etc). But not Pico "itself", so for new projects (so you don't have to care about backwards compatibility and upgrade instructions) you can safely consider the `pico-3.0` branch as stable as any stable release. Besides that one shouldn't expect much development from Pico in general, it's main feature is its simplicity, so there's not much to change to begin with. Personally I don't really see a reason not to use Pico, but due to its current state I'd recommend it for developers only. If you're looking for a more vivid (but way more complex) flat file CMS consider using Grav CMS.
