### ISSUE TITLE
simple comment system

### ISSUE THREAD

**Issue by digitalinferno** [picocms/Pico#700]
I would implement a simple comment system. The concept is to add `_comment-datenumber.md` files inside a directory named `page.id`.

So, for example, if I have a page file "my-post.md", the directory structure would be:
```
my-post.md
my-post/_comment-020202020.md
my-post/_comment-030303030.md
```
I think some plugin editor can edit these files, and I can use Pico parser for read/write tasks. My plugin reads all `_comment-*.md` files and returns an array for Twig.

The downside is the number of files. I think a blog can easily accumulate various comments for each post, which could be an issue for Pico's performance (in long term).

So I think `$skipPage` help here:

```
public function onSinglePageLoading($id, &$skipPage)
{
    if (strpos($id, '_comment-') === 0) {
       $skipPage = true;
    }
}   
```
Are there any blunders to correct?

**Comment by dkyme** [comment]
Hmm... not answering your question, but you know that there's already a comment plug-in?
https://github.com/push-eax/pico-comments
Maybe the code will help you solving your problem.

**Comment by PhrozenByte** [comment]
> The downside is the number of files. I think a blog can easily accumulate various comments for each post, which could be an issue for Pico's performance (in long term).
> 
> So I think `$skipPage` help here:

Yes, that's a good point. Having a lot of pages has a noticeable negative performance impact on Pico, so keeping the total number of pages down is a good thing. Please note that even though `$skipPage` at least prevents Pico from parsing the page, there still is some performance impact just for page discovery. Thus you might want to think about whether a single file per page containing all comments of that page might be enough. However, please note that this is no definitive answer, both approaches have advantages and disadvantages, they are both reasonable IMO. Besides, your code looks good and should work as expected.

**Comment by digitalinferno** [comment]
@dkyme thanks for the hint. Everything can be made to work, but I want to learn the correct (Pico) way :) 

So, as in many other projects, like the same pico-comments plugin, login plugin, etc., is it reasonable to move out of the content folder and create your own data structure? On paper, I don't like this solution, for the sake of cleanliness, ease of backup, and a touch of my own personal closed-mindedness.

In all functions that require knowing the ID (like this plugin, but also, for example, the one on statistics), is it correct to use `$this->pico->is404Content()` to avoid error from `$this->getPico()->getPageId($this->getPico()->getRequestFile() ?? '')`? 

Naturally, thanks as always for your availability; maybe these are obvious questions.

**Comment by PhrozenByte** [comment]
> So, as in many other projects, like the same pico-comments plugin, login plugin, etc., is it reasonable to move out of the content folder and create your own data structure?

It has both advantages and disadvantages. The biggest advantage is that such extra structure doesn't cause Pico to prematurely load the contents. The biggest disadvantage is that you have to implement the page parsing logic yourself (even though Pico provides methods for that, so that it's no big deal in the end). There's no "true" answer. However, if you choose to create your own structure, I'd always recommend moving such data into its own directory, i.e. not relying on just different file extensions.

> In all functions that require knowing the ID (like this plugin, but also, for example, the one on statistics), is it correct to use `$this->pico->is404Content()` to avoid error from `$this->getPico()->getPageId($this->getPico()->getRequestFile() ?? '')`?

`Pico::getPageId()` will work just fine for non-existing pages, it just won't work for files outside of Pico's `content` dir or files with different file extensions. Generally I'd advise against using some "path / page ID magic" to determine whether one can add comments to a page - just add a meta header (like `comments: true`) to the page's YAML Front Matter and use that. If `Pico::getPageId()` returns nothing, just forcefully disable the comments system.
