### ISSUE TITLE
Pico Edit says "unmaintained - archived", 

### ISSUE THREAD

**Issue by m-f-h** [picocms/Pico#702]
In the list of plugins (here on github, https://github.com/picocms/Pico/wiki/Pico-Plugins), there is a link to [Pico Edit](https://github.com/blocknotes/pico_edit), which however says (since at least 5 years) that it is unmaintained, and the repo is archived since 2021. This is really confusing. A note should be added in the listing. (I would do if I knew anything, but I just discover PicoCMS, I'm completely lost...)

Also, on the "plugins" page on the main website, https://picocms.org/plugins/, that (obsolete) Editor is listed. Also, I found the "Users" plugin there, but now I wonder, should I rather use "Auth" which seems more recent ?
Insofar more but I'm not an expert,  so I don't dare to edit & comment that list.)

Also, when I follow (again on the [Wiki/Plugins](https://github.com/picocms/Pico/wiki/Pico-Plugins) page), the "Content Editor" link and there the "Demo" link, the page is full of PHP errors, which makes me think that this Plugin might not work. If that's true, if would be helpful if there were a remark on the Wiki/Plugins page.

For newcomers like me, it would really be helpful to have some more guidance of what plugins can be installed and which shoulnd't be tried.

[Can I deduce that whenever the README.md says "copy to ThisPlugin..." instead of "69-ThisPlugin", it's obsolete? or are the numerical prefixes only for system/core modules?]

**Comment by PhrozenByte** [comment]
> Can I deduce that whenever the README.md says "copy to ThisPlugin..." instead of "69-ThisPlugin", it's obsolete? or are the numerical prefixes only for system/core modules?

No. There were some ideas to change plugin loading order with this, but rules were never enforced and most of the time loading order doesn't matter. Numerical prefixes have been replaced by plugin dependencies since then. They don't hurt - and give really no indication about anything.

> For newcomers like me, it would really be helpful to have some more guidance of what plugins can be installed and which shoulnd't be tried.

The plugins and themes lists are unmaintained, partially even longer than Pico itself. We never had the capacity to check compatibility with older plugins and themes, but since we tried to maintain compatibility whenever possible we didn't want to just declare plugins incompatible unless we actually know. So right now it's really just trial & error: try different plugins and see what still works. Most plugins likely still work. PHP errors like deprecation and strict notices (`E_DEPRECATED` and `E_STRICT`) can be disabled (and should be on any production server) in PHP's config (it's PHP's `error_reporting` config); they are no errors, just notes for PHP developers that PHP has changed things. `E_NOTICE` errors are actual errors in the plugin, but you can try the plugin nevertheless, they are low severity issues (still they are errors that need fixing, however, this doesn't really help when the plugin is abandoned).

>  Insofar more but I'm not an expert, so I don't dare to edit & comment that list.)

No, that's truly totally fine. As I said, we never had the capacity to check plugin compatibility, so if you find any plugin to be broken (i.e. completely unusable, not just fitting what you need), please just move it to a "Broken" section in the wiki. The wiki can be edited by anyone. Your help is very much appreciated!

> Also, I found the "Users" plugin there, but now I wonder, should I rather use "Auth" which seems more recent ?

Depends on your use case: `PicoAuth` is very powerful but quite complex, `PicoUsers` is way simpler but therefore more limited. Just try them and use what better fits your needs.

> Also, on the "plugins" page on the main website, https://picocms.org/plugins/, that (obsolete) Editor is listed.

Editor plugins always gave us some headaches. Since I never used such plugins I truly don't know which work and which don't. If you learn about what works and what doesn't, please go ahead and edit the wiki page accordingly, help is very much appreciated!
